name: Scala Development

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Scala
        uses: coursier/cache-action@v6
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Echo start
        run: echo "Starting out Scala programming..."
