name: Scala Development

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  setup:
    runs-on: [ubuntu-latest, macOs-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Script echo
        run: echo "Starting out scala programming..."
